### ISSUE TITLE
BTRFS file support does not work

### ISSUE THREAD

**Issue by dazeb** [dazeb/proxmox-dietpi-installer#11]
From the forum post below, BTRFS file support does not work and the script breaks.

Would be good to be able to ask the user the filesystem type if possible.

https://dietpi.com/forum/t/install-dietpi-on-proxmox-bash-script/15679/12?u=dazeb

**Comment by MichaIng** [comment]
This is outside the scope/possibility of this script. All it does it creating a VM from an existing DietPi image, but it does not touch the content of the image. What you need is a DietPi image with Btrfs filesystem. It is generally possible to generate one with our [build script](https://github.com/MichaIng/DietPi/blob/master/.build/images/dietpi-build), but we do not offer them so for download, as there are still some open questions, like whether compression should be enabled by default or not, and if so, which compression algorithm. And then first [this](https://github.com/MichaIng/DietPi/issues/3863) needs to be implemented.

**Comment by MichaIng** [comment]
Okay sorry for my previous (removed) post, I just did not understand the aim 😅: It is about adding support for base images with Btrfs filesystem, not for having a choice to generate a VM with either one or the other filesystem.

**Comment by dazeb** [comment]
Thanks, my apologies too, my first time opening an issue for help because I could not test the script. The testing branch has been updated with the additions from yourself. A forum user has confirmed the script working. If your happy with it i will push testing to main.
