### ISSUE TITLE
Proxmox image is now .xz not .7z

### ISSUE THREAD

**Issue by dcwestra** [dazeb/proxmox-dietpi-installer#15]
The script tries to unzip a .7z file, but only .xz files are now available for proxmox on the dietpi website. Please update the script to reflect the new file extension.

**Comment by MichaIng** [comment]
Right, I missed to update the script accordingly.

**Comment by MichaIng** [comment]
Please try it with this version of the script:
```sh
bash <(curl -sSfL https://raw.githubusercontent.com/dazeb/proxmox-dietpi-installer/xz/dietpi-install.sh)
```

**Comment by dcwestra** [comment]
flawless.

**Comment by dazeb** [comment]
Sorted, nice one 👍
