### ISSUE TITLE
Option to load custom dietpi.txt file before initial boot

### ISSUE THREAD

**Issue by Nojwe** [dazeb/proxmox-dietpi-installer#25]
Is there a way we could specify a path (local file, hosted, ftp, or something) to a custom dietpi.txt file so the first boot will run any custom scripts, install packages, etc.?

**Comment by rapjul** [comment]
Check out this line in my fork [here](https://github.com/rapjul/proxmox-dietpi-installer/blob/production/dietpi-install.sh#L130).

```sh
virt-customize -a "${VM_IMAGE_NAME}" --upload "${BOOT_FILE}":/boot
```

Make sure the `libguestfs-tools` package is installed first.

**Comment by Nojwe** [comment]
Oh sweet, thank you!

**Comment by dazeb** [comment]
We would add it to the main script but the aim is to keep it simple so that others can build on it. @rapjul has the perfect response.

**Comment by Nojwe** [comment]
Makes sense. Thank you both!
