### ISSUE TITLE
7zr not found - add check for 7zip

### ISSUE THREAD

**Issue by quorn23** [dazeb/proxmox-dietpi-installer#5]
Small feedback from someone with a fresh proxmox installation

7zip is missing, so line 22 fails to extract the vm and the script proceeds to create an empty vm.

A small check if p7zip-full (for example) is installed and if not installs it first would be a convinient addition.

Something like
`#!/bin/bash

if ! command -v 7z &> /dev/null
then
    echo "p7zip-full is not installed, installing..."
    apt-get update
    apt-get install -y p7zip-full
    echo "p7zip-full installed successfully!"
else
    echo "p7zip-full is already installed"
fi
`

before image extraction should do the trick probably.

**Comment by MichaIng** [comment]
It uses `7zr`, so `apt install p7zip` is sufficient, no need for the full package. But jep, makes sense to install this as part of the script.

**Comment by MichaIng** [comment]
PR up: #6
